<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\navidataIO.Utils\navidataIO.Utils.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.extensibility.execution" />
    <PackageReference Include="Serilog" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <Using Remove="Microsoft.Extensions.Logging" />
  </ItemGroup>
</Project>