<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.7" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="Serilog" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.extensibility.core" Version="2.9.3" />
    <PackageVersion Include="xunit.extensibility.execution" Version="2.9.3" />
    <PackageVersion Include="xunit.v3" Version="2.0.3" />
    <PackageVersion Include="xunit.v3.extensibility.core" Version="2.0.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.1" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
  </ItemGroup>
  <ItemGroup>
    <GlobalPackageReference Include="DotNet.ReproducibleBuilds" Version="1.2.25" />
    <GlobalPackageReference Include="GitVersion.MsBuild" Version="6.3.0" />
  </ItemGroup>
</Project>