<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FabricTools.Utils\FabricTools.Utils.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit" />
    <PackageReference Include="Serilog" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>