<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\FabricTools.Utils.Testing.Shared\Testing\**\*.cs" LinkBase="Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FabricTools.Utils\FabricTools.Utils.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>