<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup>
    <RootNamespace>FabricTools.Utils</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageIcon>FabricTools.png</PackageIcon>
    <IncludeSymbols>true</IncludeSymbols>
    <IncludeSource>true</IncludeSource>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\FabricTools.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GitVersion.MsBuild">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.Extensions.Logging" />
  </ItemGroup>

</Project>